(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module arena.
  (* StructRecord
    {
      name := "Arena";
      const_params := [];
      ty_params := [];
      fields :=
        [
          ("mem",
            Ty.apply
              (Ty.path "&mut")
              []
              [ Ty.apply (Ty.path "slice") [] [ Ty.path "encore_vm::value::Value" ] ]);
          ("hp", Ty.path "usize")
        ];
    } *)
  
  Module Impl_encore_vm_arena_Arena.
    Definition Self : Ty.t := Ty.path "encore_vm::arena::Arena".
    
    (*
        pub fn new(mem: &'a mut [Value]) -> Self {
            Self {
                mem,
                hp: 0,
                #[cfg(feature = "stats")]
                stats: ArenaStats::default(),
            }
        }
    *)
    Definition new (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ mem ] =>
        ltac:(M.monadic
          (let mem :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "slice") [] [ Ty.path "encore_vm::value::Value" ] ],
              mem
            |) in
          Value.mkStructRecord
            "encore_vm::arena::Arena"
            []
            []
            [
              ("mem", M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| mem |) |) |));
              ("hp", Value.Integer IntegerKind.Usize 0)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new : M.IsAssociatedFunction.C Self "new" new.
    Admitted.
    Global Typeclasses Opaque new.
    
    (*     pub fn hp(&self) -> usize { self.hp } *)
    Definition hp (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::arena::Arena" ], self |) in
          M.read (|
            M.SubPointer.get_struct_record_field (|
              M.deref (| M.read (| self |) |),
              "encore_vm::arena::Arena",
              "hp"
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_hp : M.IsAssociatedFunction.C Self "hp" hp.
    Admitted.
    Global Typeclasses Opaque hp.
    
    (*
        pub fn alloc(
            &mut self,
            n: usize,
            roots: &mut [Value],
            globals: &mut [Value],
        ) -> Result<HeapAddress, VmError> {
            if self.hp + n > self.mem.len() {
                gc::collect(self, roots, globals);
                if self.hp + n > self.mem.len() {
                    return Err(VmError::HeapOverflow);
                }
            }
            let addr = HeapAddress::new(self.hp as u16);
            self.hp += n;
            #[cfg(feature = "stats")]
            if self.hp > self.stats.peak_heap { self.stats.peak_heap = self.hp; }
            Ok(addr)
        }
    *)
    Definition alloc (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; n; roots; globals ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::arena::Arena" ],
              self
            |) in
          let n := M.alloc (| Ty.path "usize", n |) in
          let roots :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "slice") [] [ Ty.path "encore_vm::value::Value" ] ],
              roots
            |) in
          let globals :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "slice") [] [ Ty.path "encore_vm::value::Value" ] ],
              globals
            |) in
          M.catch_return
            (Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.path "encore_vm::value::HeapAddress"; Ty.path "encore_vm::error::VmError" ]) (|
            ltac:(M.monadic
              (M.read (|
                let~ _ : Ty.tuple [] :=
                  M.match_operator (|
                    Ty.tuple [],
                    M.alloc (| Ty.tuple [], Value.Tuple [] |),
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (let γ :=
                            M.use
                              (M.alloc (|
                                Ty.path "bool",
                                M.call_closure (|
                                  Ty.path "bool",
                                  BinOp.gt,
                                  [
                                    M.call_closure (|
                                      Ty.path "usize",
                                      BinOp.Wrap.add,
                                      [
                                        M.read (|
                                          M.SubPointer.get_struct_record_field (|
                                            M.deref (| M.read (| self |) |),
                                            "encore_vm::arena::Arena",
                                            "hp"
                                          |)
                                        |);
                                        M.read (| n |)
                                      ]
                                    |);
                                    M.call_closure (|
                                      Ty.path "usize",
                                      M.get_associated_function (|
                                        Ty.apply
                                          (Ty.path "slice")
                                          []
                                          [ Ty.path "encore_vm::value::Value" ],
                                        "len",
                                        [],
                                        []
                                      |),
                                      [
                                        M.borrow (|
                                          Pointer.Kind.Ref,
                                          M.deref (|
                                            M.read (|
                                              M.SubPointer.get_struct_record_field (|
                                                M.deref (| M.read (| self |) |),
                                                "encore_vm::arena::Arena",
                                                "mem"
                                              |)
                                            |)
                                          |)
                                        |)
                                      ]
                                    |)
                                  ]
                                |)
                              |)) in
                          let _ :=
                            is_constant_or_break_match (| M.read (| γ |), Value.Bool true |) in
                          M.read (|
                            let~ _ : Ty.tuple [] :=
                              M.call_closure (|
                                Ty.tuple [],
                                M.get_function (| "encore_vm::gc::collect", [], [] |),
                                [
                                  M.borrow (|
                                    Pointer.Kind.MutRef,
                                    M.deref (| M.read (| self |) |)
                                  |);
                                  M.borrow (|
                                    Pointer.Kind.MutRef,
                                    M.deref (| M.read (| roots |) |)
                                  |);
                                  M.borrow (|
                                    Pointer.Kind.MutRef,
                                    M.deref (| M.read (| globals |) |)
                                  |)
                                ]
                              |) in
                            M.alloc (|
                              Ty.tuple [],
                              M.match_operator (|
                                Ty.tuple [],
                                M.alloc (| Ty.tuple [], Value.Tuple [] |),
                                [
                                  fun γ =>
                                    ltac:(M.monadic
                                      (let γ :=
                                        M.use
                                          (M.alloc (|
                                            Ty.path "bool",
                                            M.call_closure (|
                                              Ty.path "bool",
                                              BinOp.gt,
                                              [
                                                M.call_closure (|
                                                  Ty.path "usize",
                                                  BinOp.Wrap.add,
                                                  [
                                                    M.read (|
                                                      M.SubPointer.get_struct_record_field (|
                                                        M.deref (| M.read (| self |) |),
                                                        "encore_vm::arena::Arena",
                                                        "hp"
                                                      |)
                                                    |);
                                                    M.read (| n |)
                                                  ]
                                                |);
                                                M.call_closure (|
                                                  Ty.path "usize",
                                                  M.get_associated_function (|
                                                    Ty.apply
                                                      (Ty.path "slice")
                                                      []
                                                      [ Ty.path "encore_vm::value::Value" ],
                                                    "len",
                                                    [],
                                                    []
                                                  |),
                                                  [
                                                    M.borrow (|
                                                      Pointer.Kind.Ref,
                                                      M.deref (|
                                                        M.read (|
                                                          M.SubPointer.get_struct_record_field (|
                                                            M.deref (| M.read (| self |) |),
                                                            "encore_vm::arena::Arena",
                                                            "mem"
                                                          |)
                                                        |)
                                                      |)
                                                    |)
                                                  ]
                                                |)
                                              ]
                                            |)
                                          |)) in
                                      let _ :=
                                        is_constant_or_break_match (|
                                          M.read (| γ |),
                                          Value.Bool true
                                        |) in
                                      M.never_to_any (|
                                        M.read (|
                                          M.return_ (|
                                            Value.StructTuple
                                              "core::result::Result::Err"
                                              []
                                              [
                                                Ty.path "encore_vm::value::HeapAddress";
                                                Ty.path "encore_vm::error::VmError"
                                              ]
                                              [
                                                Value.StructTuple
                                                  "encore_vm::error::VmError::HeapOverflow"
                                                  []
                                                  []
                                                  []
                                              ]
                                          |)
                                        |)
                                      |)));
                                  fun γ => ltac:(M.monadic (Value.Tuple []))
                                ]
                              |)
                            |)
                          |)));
                      fun γ => ltac:(M.monadic (Value.Tuple []))
                    ]
                  |) in
                let~ addr : Ty.path "encore_vm::value::HeapAddress" :=
                  M.call_closure (|
                    Ty.path "encore_vm::value::HeapAddress",
                    M.get_associated_function (|
                      Ty.path "encore_vm::value::HeapAddress",
                      "new",
                      [],
                      []
                    |),
                    [
                      M.cast
                        (Ty.path "u16")
                        (M.read (|
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "encore_vm::arena::Arena",
                            "hp"
                          |)
                        |))
                    ]
                  |) in
                let~ _ : Ty.tuple [] :=
                  let β :=
                    M.SubPointer.get_struct_record_field (|
                      M.deref (| M.read (| self |) |),
                      "encore_vm::arena::Arena",
                      "hp"
                    |) in
                  M.write (|
                    β,
                    M.call_closure (|
                      Ty.path "usize",
                      BinOp.Wrap.add,
                      [ M.read (| β |); M.read (| n |) ]
                    |)
                  |) in
                M.alloc (|
                  Ty.apply
                    (Ty.path "core::result::Result")
                    []
                    [ Ty.path "encore_vm::value::HeapAddress"; Ty.path "encore_vm::error::VmError"
                    ],
                  Value.StructTuple
                    "core::result::Result::Ok"
                    []
                    [ Ty.path "encore_vm::value::HeapAddress"; Ty.path "encore_vm::error::VmError" ]
                    [ M.read (| addr |) ]
                |)
              |)))
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_alloc : M.IsAssociatedFunction.C Self "alloc" alloc.
    Admitted.
    Global Typeclasses Opaque alloc.
    
    (*
        pub fn heap_read(&self, addr: HeapAddress, off: usize) -> Value {
            unsafe { *self.mem.get_unchecked(addr.offset(off)) }
        }
    *)
    Definition heap_read (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; addr; off ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::arena::Arena" ], self |) in
          let addr := M.alloc (| Ty.path "encore_vm::value::HeapAddress", addr |) in
          let off := M.alloc (| Ty.path "usize", off |) in
          M.read (|
            M.deref (|
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::value::Value" ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "slice") [] [ Ty.path "encore_vm::value::Value" ],
                  "get_unchecked",
                  [],
                  [ Ty.path "usize" ]
                |),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.read (|
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "encore_vm::arena::Arena",
                          "mem"
                        |)
                      |)
                    |)
                  |);
                  M.call_closure (|
                    Ty.path "usize",
                    M.get_associated_function (|
                      Ty.path "encore_vm::value::HeapAddress",
                      "offset",
                      [],
                      []
                    |),
                    [ M.read (| addr |); M.read (| off |) ]
                  |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_heap_read :
      M.IsAssociatedFunction.C Self "heap_read" heap_read.
    Admitted.
    Global Typeclasses Opaque heap_read.
    
    (*
        pub fn heap_write(&mut self, addr: HeapAddress, off: usize, val: Value) {
            unsafe { *self.mem.get_unchecked_mut(addr.offset(off)) = val; }
        }
    *)
    Definition heap_write (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; addr; off; val ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::arena::Arena" ],
              self
            |) in
          let addr := M.alloc (| Ty.path "encore_vm::value::HeapAddress", addr |) in
          let off := M.alloc (| Ty.path "usize", off |) in
          let val := M.alloc (| Ty.path "encore_vm::value::Value", val |) in
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.write (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::value::Value" ],
                    M.get_associated_function (|
                      Ty.apply (Ty.path "slice") [] [ Ty.path "encore_vm::value::Value" ],
                      "get_unchecked_mut",
                      [],
                      [ Ty.path "usize" ]
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.MutRef,
                        M.deref (|
                          M.read (|
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| self |) |),
                              "encore_vm::arena::Arena",
                              "mem"
                            |)
                          |)
                        |)
                      |);
                      M.call_closure (|
                        Ty.path "usize",
                        M.get_associated_function (|
                          Ty.path "encore_vm::value::HeapAddress",
                          "offset",
                          [],
                          []
                        |),
                        [ M.read (| addr |); M.read (| off |) ]
                      |)
                    ]
                  |)
                |),
                M.read (| val |)
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_heap_write :
      M.IsAssociatedFunction.C Self "heap_write" heap_write.
    Admitted.
    Global Typeclasses Opaque heap_write.
  End Impl_encore_vm_arena_Arena.
End arena.
