(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module value.
  Definition value_TYP_CLOS (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 0 |))).
  
  Global Instance Instance_IsConstant_value_TYP_CLOS :
    M.IsFunction.C "encore_vm::value::TYP_CLOS" value_TYP_CLOS.
  Admitted.
  Global Typeclasses Opaque value_TYP_CLOS.
  
  Definition value_TYP_CTOR (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 1 |))).
  
  Global Instance Instance_IsConstant_value_TYP_CTOR :
    M.IsFunction.C "encore_vm::value::TYP_CTOR" value_TYP_CTOR.
  Admitted.
  Global Typeclasses Opaque value_TYP_CTOR.
  
  Definition value_TYP_HDR (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 2 |))).
  
  Global Instance Instance_IsConstant_value_TYP_HDR :
    M.IsFunction.C "encore_vm::value::TYP_HDR" value_TYP_HDR.
  Admitted.
  Global Typeclasses Opaque value_TYP_HDR.
  
  Definition value_TYP_GC (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 3 |))).
  
  Global Instance Instance_IsConstant_value_TYP_GC :
    M.IsFunction.C "encore_vm::value::TYP_GC" value_TYP_GC.
  Admitted.
  Global Typeclasses Opaque value_TYP_GC.
  
  Definition value_TYP_INT (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 4 |))).
  
  Global Instance Instance_IsConstant_value_TYP_INT :
    M.IsFunction.C "encore_vm::value::TYP_INT" value_TYP_INT.
  Admitted.
  Global Typeclasses Opaque value_TYP_INT.
  
  Definition value_TYP_FUNC (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 5 |))).
  
  Global Instance Instance_IsConstant_value_TYP_FUNC :
    M.IsFunction.C "encore_vm::value::TYP_FUNC" value_TYP_FUNC.
  Admitted.
  Global Typeclasses Opaque value_TYP_FUNC.
  
  Definition value_TYP_BYTES (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 6 |))).
  
  Global Instance Instance_IsConstant_value_TYP_BYTES :
    M.IsFunction.C "encore_vm::value::TYP_BYTES" value_TYP_BYTES.
  Admitted.
  Global Typeclasses Opaque value_TYP_BYTES.
  
  Definition value_TYP_BYTES_HDR (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u32", Value.Integer IntegerKind.U32 7 |))).
  
  Global Instance Instance_IsConstant_value_TYP_BYTES_HDR :
    M.IsFunction.C "encore_vm::value::TYP_BYTES_HDR" value_TYP_BYTES_HDR.
  Admitted.
  Global Typeclasses Opaque value_TYP_BYTES_HDR.
  
  Definition value_GC_MARK_BIT (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic
      (M.alloc (|
        Ty.path "u32",
        M.call_closure (|
          Ty.path "u32",
          BinOp.Wrap.shl,
          [ Value.Integer IntegerKind.U32 128; Value.Integer IntegerKind.I32 8 ]
        |)
      |))).
  
  Global Instance Instance_IsConstant_value_GC_MARK_BIT :
    M.IsFunction.C "encore_vm::value::GC_MARK_BIT" value_GC_MARK_BIT.
  Admitted.
  Global Typeclasses Opaque value_GC_MARK_BIT.
  
  (* StructTuple
    {
      name := "HeapAddress";
      const_params := [];
      ty_params := [];
      fields := [ Ty.path "u16" ];
    } *)
  
  Module Impl_core_clone_Clone_for_encore_vm_value_HeapAddress.
    Definition Self : Ty.t := Ty.path "encore_vm::value::HeapAddress".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::value::HeapAddress" ],
              self
            |) in
          M.match_operator (|
            Ty.path "encore_vm::value::HeapAddress",
            Value.DeclaredButUndefined,
            [ fun γ => ltac:(M.monadic (M.read (| M.deref (| M.read (| self |) |) |))) ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_encore_vm_value_HeapAddress.
  
  Module Impl_core_marker_Copy_for_encore_vm_value_HeapAddress.
    Definition Self : Ty.t := Ty.path "encore_vm::value::HeapAddress".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::Copy"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_Copy_for_encore_vm_value_HeapAddress.
  
  Module Impl_encore_vm_value_HeapAddress.
    Definition Self : Ty.t := Ty.path "encore_vm::value::HeapAddress".
    
    (*     pub const NULL: Self = Self(u16::MAX); *)
    (* Ty.path "encore_vm::value::HeapAddress" *)
    Definition value_NULL (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      ltac:(M.monadic
        (M.alloc (|
          Ty.path "encore_vm::value::HeapAddress",
          Value.StructTuple
            "encore_vm::value::HeapAddress"
            []
            []
            [ M.read (| get_associated_constant (| Ty.path "u16", "MAX", Ty.path "u16" |) |) ]
        |))).
    
    Global Instance AssociatedConstant_value_NULL : M.IsAssociatedFunction.C Self "NULL" value_NULL.
    Admitted.
    Global Typeclasses Opaque value_NULL.
    
    (*     pub fn new(raw: u16) -> Self { Self(raw) } *)
    Definition new (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ raw ] =>
        ltac:(M.monadic
          (let raw := M.alloc (| Ty.path "u16", raw |) in
          Value.StructTuple "encore_vm::value::HeapAddress" [] [] [ M.read (| raw |) ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new : M.IsAssociatedFunction.C Self "new" new.
    Admitted.
    Global Typeclasses Opaque new.
    
    (*     pub fn is_null(self) -> bool { self.0 == u16::MAX } *)
    Definition is_null (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::HeapAddress", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.read (|
                M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::HeapAddress", 0 |)
              |);
              M.read (| get_associated_constant (| Ty.path "u16", "MAX", Ty.path "u16" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_null : M.IsAssociatedFunction.C Self "is_null" is_null.
    Admitted.
    Global Typeclasses Opaque is_null.
    
    (*     pub fn offset(self, off: usize) -> usize { self.0 as usize + off } *)
    Definition offset (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; off ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::HeapAddress", self |) in
          let off := M.alloc (| Ty.path "usize", off |) in
          M.call_closure (|
            Ty.path "usize",
            BinOp.Wrap.add,
            [
              M.cast
                (Ty.path "usize")
                (M.read (|
                  M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::HeapAddress", 0 |)
                |));
              M.read (| off |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_offset : M.IsAssociatedFunction.C Self "offset" offset.
    Admitted.
    Global Typeclasses Opaque offset.
    
    (*     pub fn raw(self) -> u16 { self.0 } *)
    Definition raw (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::HeapAddress", self |) in
          M.read (|
            M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::HeapAddress", 0 |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_raw : M.IsAssociatedFunction.C Self "raw" raw.
    Admitted.
    Global Typeclasses Opaque raw.
  End Impl_encore_vm_value_HeapAddress.
  
  (* StructTuple
    {
      name := "Reg";
      const_params := [];
      ty_params := [];
      fields := [ Ty.path "u8" ];
    } *)
  
  Module Impl_core_clone_Clone_for_encore_vm_value_Reg.
    Definition Self : Ty.t := Ty.path "encore_vm::value::Reg".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::value::Reg" ], self |) in
          M.match_operator (|
            Ty.path "encore_vm::value::Reg",
            Value.DeclaredButUndefined,
            [ fun γ => ltac:(M.monadic (M.read (| M.deref (| M.read (| self |) |) |))) ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_encore_vm_value_Reg.
  
  Module Impl_core_marker_Copy_for_encore_vm_value_Reg.
    Definition Self : Ty.t := Ty.path "encore_vm::value::Reg".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::Copy"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_Copy_for_encore_vm_value_Reg.
  
  Module Impl_encore_vm_value_Reg.
    Definition Self : Ty.t := Ty.path "encore_vm::value::Reg".
    
    (*     pub const fn new(raw: u8) -> Self { Self(raw) } *)
    Definition new (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ raw ] =>
        ltac:(M.monadic
          (let raw := M.alloc (| Ty.path "u8", raw |) in
          Value.StructTuple "encore_vm::value::Reg" [] [] [ M.read (| raw |) ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new : M.IsAssociatedFunction.C Self "new" new.
    Admitted.
    Global Typeclasses Opaque new.
    
    (*     pub fn idx(self) -> usize { self.0 as usize } *)
    Definition idx (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Reg", self |) in
          M.cast
            (Ty.path "usize")
            (M.read (|
              M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Reg", 0 |)
            |))))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_idx : M.IsAssociatedFunction.C Self "idx" idx.
    Admitted.
    Global Typeclasses Opaque idx.
    
    (*     pub fn offset(self, n: usize) -> usize { self.0 as usize + n } *)
    Definition offset (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; n ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Reg", self |) in
          let n := M.alloc (| Ty.path "usize", n |) in
          M.call_closure (|
            Ty.path "usize",
            BinOp.Wrap.add,
            [
              M.cast
                (Ty.path "usize")
                (M.read (|
                  M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Reg", 0 |)
                |));
              M.read (| n |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_offset : M.IsAssociatedFunction.C Self "offset" offset.
    Admitted.
    Global Typeclasses Opaque offset.
  End Impl_encore_vm_value_Reg.
  
  (* StructTuple
    {
      name := "CodeAddress";
      const_params := [];
      ty_params := [];
      fields := [ Ty.path "u16" ];
    } *)
  
  Module Impl_core_clone_Clone_for_encore_vm_value_CodeAddress.
    Definition Self : Ty.t := Ty.path "encore_vm::value::CodeAddress".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::value::CodeAddress" ],
              self
            |) in
          M.match_operator (|
            Ty.path "encore_vm::value::CodeAddress",
            Value.DeclaredButUndefined,
            [ fun γ => ltac:(M.monadic (M.read (| M.deref (| M.read (| self |) |) |))) ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_encore_vm_value_CodeAddress.
  
  Module Impl_core_marker_Copy_for_encore_vm_value_CodeAddress.
    Definition Self : Ty.t := Ty.path "encore_vm::value::CodeAddress".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::Copy"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_Copy_for_encore_vm_value_CodeAddress.
  
  Module Impl_core_fmt_Debug_for_encore_vm_value_CodeAddress.
    Definition Self : Ty.t := Ty.path "encore_vm::value::CodeAddress".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::value::CodeAddress" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (|
              Ty.path "core::fmt::Formatter",
              "debug_tuple_field1_finish",
              [],
              []
            |),
            [
              M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "CodeAddress" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "&") [] [ Ty.path "u16" ] ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.alloc (|
                          Ty.apply (Ty.path "&") [] [ Ty.path "u16" ],
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.SubPointer.get_struct_tuple_field (|
                              M.deref (| M.read (| self |) |),
                              "encore_vm::value::CodeAddress",
                              0
                            |)
                          |)
                        |)
                      |)
                    |)
                  |)
                ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_encore_vm_value_CodeAddress.
  
  Module Impl_encore_vm_value_CodeAddress.
    Definition Self : Ty.t := Ty.path "encore_vm::value::CodeAddress".
    
    (*     pub fn new(raw: u16) -> Self { Self(raw) } *)
    Definition new (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ raw ] =>
        ltac:(M.monadic
          (let raw := M.alloc (| Ty.path "u16", raw |) in
          Value.StructTuple "encore_vm::value::CodeAddress" [] [] [ M.read (| raw |) ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new : M.IsAssociatedFunction.C Self "new" new.
    Admitted.
    Global Typeclasses Opaque new.
    
    (*     pub fn raw(self) -> u16 { self.0 } *)
    Definition raw (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::CodeAddress", self |) in
          M.read (|
            M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::CodeAddress", 0 |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_raw : M.IsAssociatedFunction.C Self "raw" raw.
    Admitted.
    Global Typeclasses Opaque raw.
  End Impl_encore_vm_value_CodeAddress.
  
  (* StructTuple
    {
      name := "Value";
      const_params := [];
      ty_params := [];
      fields := [ Ty.path "u32" ];
    } *)
  
  Module Impl_core_clone_Clone_for_encore_vm_value_Value.
    Definition Self : Ty.t := Ty.path "encore_vm::value::Value".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::value::Value" ], self |) in
          M.match_operator (|
            Ty.path "encore_vm::value::Value",
            Value.DeclaredButUndefined,
            [ fun γ => ltac:(M.monadic (M.read (| M.deref (| M.read (| self |) |) |))) ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_encore_vm_value_Value.
  
  Module Impl_core_marker_Copy_for_encore_vm_value_Value.
    Definition Self : Ty.t := Ty.path "encore_vm::value::Value".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::Copy"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_Copy_for_encore_vm_value_Value.
  
  Module Impl_encore_vm_value_Value.
    Definition Self : Ty.t := Ty.path "encore_vm::value::Value".
    
    (*     pub const ZERO: Self = Self(0); *)
    (* Ty.path "encore_vm::value::Value" *)
    Definition value_ZERO (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      ltac:(M.monadic
        (M.alloc (|
          Ty.path "encore_vm::value::Value",
          Value.StructTuple "encore_vm::value::Value" [] [] [ Value.Integer IntegerKind.U32 0 ]
        |))).
    
    Global Instance AssociatedConstant_value_ZERO : M.IsAssociatedFunction.C Self "ZERO" value_ZERO.
    Admitted.
    Global Typeclasses Opaque value_ZERO.
    
    (*
        pub fn function(code_ptr: CodeAddress) -> Self {
            Self(TYP_FUNC | (code_ptr.raw() as u32) << 16)
        }
    *)
    Definition function (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ code_ptr ] =>
        ltac:(M.monadic
          (let code_ptr := M.alloc (| Ty.path "encore_vm::value::CodeAddress", code_ptr |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.read (| get_constant (| "encore_vm::value::TYP_FUNC", Ty.path "u32" |) |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast
                        (Ty.path "u32")
                        (M.call_closure (|
                          Ty.path "u16",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::CodeAddress",
                            "raw",
                            [],
                            []
                          |),
                          [ M.read (| code_ptr |) ]
                        |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_function : M.IsAssociatedFunction.C Self "function" function.
    Admitted.
    Global Typeclasses Opaque function.
    
    (*
        pub const fn function_const(code_ptr_raw: u16) -> Self {
            Self(TYP_FUNC | (code_ptr_raw as u32) << 16)
        }
    *)
    Definition function_const (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ code_ptr_raw ] =>
        ltac:(M.monadic
          (let code_ptr_raw := M.alloc (| Ty.path "u16", code_ptr_raw |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.read (| get_constant (| "encore_vm::value::TYP_FUNC", Ty.path "u32" |) |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast (Ty.path "u32") (M.read (| code_ptr_raw |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_function_const :
      M.IsAssociatedFunction.C Self "function_const" function_const.
    Admitted.
    Global Typeclasses Opaque function_const.
    
    (*
        pub fn closure(addr: HeapAddress) -> Self {
            Self(TYP_CLOS | (addr.raw() as u32) << 16)
        }
    *)
    Definition closure (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ addr ] =>
        ltac:(M.monadic
          (let addr := M.alloc (| Ty.path "encore_vm::value::HeapAddress", addr |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.read (| get_constant (| "encore_vm::value::TYP_CLOS", Ty.path "u32" |) |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast
                        (Ty.path "u32")
                        (M.call_closure (|
                          Ty.path "u16",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::HeapAddress",
                            "raw",
                            [],
                            []
                          |),
                          [ M.read (| addr |) ]
                        |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_closure : M.IsAssociatedFunction.C Self "closure" closure.
    Admitted.
    Global Typeclasses Opaque closure.
    
    (*
        pub fn ctor(tag: u8, addr: HeapAddress) -> Self {
            Self(TYP_CTOR | (tag as u32) << 8 | (addr.raw() as u32) << 16)
        }
    *)
    Definition ctor (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ tag; addr ] =>
        ltac:(M.monadic
          (let tag := M.alloc (| Ty.path "u8", tag |) in
          let addr := M.alloc (| Ty.path "encore_vm::value::HeapAddress", addr |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.bit_or,
                    [
                      M.read (| get_constant (| "encore_vm::value::TYP_CTOR", Ty.path "u32" |) |);
                      M.call_closure (|
                        Ty.path "u32",
                        BinOp.Wrap.shl,
                        [ M.cast (Ty.path "u32") (M.read (| tag |)); Value.Integer IntegerKind.I32 8
                        ]
                      |)
                    ]
                  |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast
                        (Ty.path "u32")
                        (M.call_closure (|
                          Ty.path "u16",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::HeapAddress",
                            "raw",
                            [],
                            []
                          |),
                          [ M.read (| addr |) ]
                        |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_ctor : M.IsAssociatedFunction.C Self "ctor" ctor.
    Admitted.
    Global Typeclasses Opaque ctor.
    
    (*
        pub fn closure_header(env_len: u8, code_ptr: CodeAddress) -> Self {
            Self(TYP_HDR | (env_len as u32) << 8 | (code_ptr.raw() as u32) << 16)
        }
    *)
    Definition closure_header (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ env_len; code_ptr ] =>
        ltac:(M.monadic
          (let env_len := M.alloc (| Ty.path "u8", env_len |) in
          let code_ptr := M.alloc (| Ty.path "encore_vm::value::CodeAddress", code_ptr |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.bit_or,
                    [
                      M.read (| get_constant (| "encore_vm::value::TYP_HDR", Ty.path "u32" |) |);
                      M.call_closure (|
                        Ty.path "u32",
                        BinOp.Wrap.shl,
                        [
                          M.cast (Ty.path "u32") (M.read (| env_len |));
                          Value.Integer IntegerKind.I32 8
                        ]
                      |)
                    ]
                  |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast
                        (Ty.path "u32")
                        (M.call_closure (|
                          Ty.path "u16",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::CodeAddress",
                            "raw",
                            [],
                            []
                          |),
                          [ M.read (| code_ptr |) ]
                        |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_closure_header :
      M.IsAssociatedFunction.C Self "closure_header" closure_header.
    Admitted.
    Global Typeclasses Opaque closure_header.
    
    (*
        pub fn int(n: i32) -> Self {
            Self(TYP_INT | ((n as u32 & 0x00FF_FFFF) << 8))
        }
    *)
    Definition int (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ n ] =>
        ltac:(M.monadic
          (let n := M.alloc (| Ty.path "i32", n |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.read (| get_constant (| "encore_vm::value::TYP_INT", Ty.path "u32" |) |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.call_closure (|
                        Ty.path "u32",
                        BinOp.Wrap.bit_and,
                        [
                          M.cast (Ty.path "u32") (M.read (| n |));
                          Value.Integer IntegerKind.U32 16777215
                        ]
                      |);
                      Value.Integer IntegerKind.I32 8
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_int : M.IsAssociatedFunction.C Self "int" int.
    Admitted.
    Global Typeclasses Opaque int.
    
    (*
        pub fn bytes(addr: HeapAddress) -> Self {
            Self(TYP_BYTES | (addr.raw() as u32) << 16)
        }
    *)
    Definition bytes (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ addr ] =>
        ltac:(M.monadic
          (let addr := M.alloc (| Ty.path "encore_vm::value::HeapAddress", addr |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.read (| get_constant (| "encore_vm::value::TYP_BYTES", Ty.path "u32" |) |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast
                        (Ty.path "u32")
                        (M.call_closure (|
                          Ty.path "u16",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::HeapAddress",
                            "raw",
                            [],
                            []
                          |),
                          [ M.read (| addr |) ]
                        |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_bytes : M.IsAssociatedFunction.C Self "bytes" bytes.
    Admitted.
    Global Typeclasses Opaque bytes.
    
    (*
        pub fn bytes_header(byte_len: usize) -> Self {
            Self(TYP_BYTES_HDR | (byte_len as u32) << 8)
        }
    *)
    Definition bytes_header (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ byte_len ] =>
        ltac:(M.monadic
          (let byte_len := M.alloc (| Ty.path "usize", byte_len |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.read (| get_constant (| "encore_vm::value::TYP_BYTES_HDR", Ty.path "u32" |) |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast (Ty.path "u32") (M.read (| byte_len |));
                      Value.Integer IntegerKind.I32 8
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_bytes_header :
      M.IsAssociatedFunction.C Self "bytes_header" bytes_header.
    Admitted.
    Global Typeclasses Opaque bytes_header.
    
    (*     pub fn is_function(self) -> bool { self.0 & 0xFF == TYP_FUNC } *)
    Definition is_function (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_FUNC", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_function :
      M.IsAssociatedFunction.C Self "is_function" is_function.
    Admitted.
    Global Typeclasses Opaque is_function.
    
    (*     pub fn is_closure(self) -> bool { self.0 & 0xFF == TYP_CLOS } *)
    Definition is_closure (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_CLOS", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_closure :
      M.IsAssociatedFunction.C Self "is_closure" is_closure.
    Admitted.
    Global Typeclasses Opaque is_closure.
    
    (*     pub fn is_ctor(self) -> bool { self.0 & 0xFF == TYP_CTOR } *)
    Definition is_ctor (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_CTOR", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_ctor : M.IsAssociatedFunction.C Self "is_ctor" is_ctor.
    Admitted.
    Global Typeclasses Opaque is_ctor.
    
    (*     pub fn is_header(self) -> bool { self.0 & 0xFF == TYP_HDR } *)
    Definition is_header (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_HDR", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_header :
      M.IsAssociatedFunction.C Self "is_header" is_header.
    Admitted.
    Global Typeclasses Opaque is_header.
    
    (*     pub fn is_int(self) -> bool { self.0 & 0xFF == TYP_INT } *)
    Definition is_int (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_INT", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_int : M.IsAssociatedFunction.C Self "is_int" is_int.
    Admitted.
    Global Typeclasses Opaque is_int.
    
    (*     pub fn is_bytes(self) -> bool { self.0 & 0xFF == TYP_BYTES } *)
    Definition is_bytes (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_BYTES", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_bytes : M.IsAssociatedFunction.C Self "is_bytes" is_bytes.
    Admitted.
    Global Typeclasses Opaque is_bytes.
    
    (*     pub fn is_bytes_hdr(self) -> bool { self.0 & 0xFF == TYP_BYTES_HDR } *)
    Definition is_bytes_hdr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_BYTES_HDR", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_bytes_hdr :
      M.IsAssociatedFunction.C Self "is_bytes_hdr" is_bytes_hdr.
    Admitted.
    Global Typeclasses Opaque is_bytes_hdr.
    
    (*     pub fn code_ptr(self) -> CodeAddress { CodeAddress((self.0 >> 16) as u16) } *)
    Definition code_ptr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::CodeAddress"
            []
            []
            [
              M.cast
                (Ty.path "u16")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 16
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_code_ptr : M.IsAssociatedFunction.C Self "code_ptr" code_ptr.
    Admitted.
    Global Typeclasses Opaque code_ptr.
    
    (*     pub fn closure_addr(self) -> HeapAddress { HeapAddress((self.0 >> 16) as u16) } *)
    Definition closure_addr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::HeapAddress"
            []
            []
            [
              M.cast
                (Ty.path "u16")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 16
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_closure_addr :
      M.IsAssociatedFunction.C Self "closure_addr" closure_addr.
    Admitted.
    Global Typeclasses Opaque closure_addr.
    
    (*     pub fn ctor_tag(self) -> u8 { (self.0 >> 8) as u8 } *)
    Definition ctor_tag (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.cast
            (Ty.path "u8")
            (M.call_closure (|
              Ty.path "u32",
              BinOp.Wrap.shr,
              [
                M.read (|
                  M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                |);
                Value.Integer IntegerKind.I32 8
              ]
            |))))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_ctor_tag : M.IsAssociatedFunction.C Self "ctor_tag" ctor_tag.
    Admitted.
    Global Typeclasses Opaque ctor_tag.
    
    (*     pub fn ctor_addr(self) -> HeapAddress { HeapAddress((self.0 >> 16) as u16) } *)
    Definition ctor_addr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::HeapAddress"
            []
            []
            [
              M.cast
                (Ty.path "u16")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 16
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_ctor_addr :
      M.IsAssociatedFunction.C Self "ctor_addr" ctor_addr.
    Admitted.
    Global Typeclasses Opaque ctor_addr.
    
    (*     pub fn bytes_addr(self) -> HeapAddress { HeapAddress((self.0 >> 16) as u16) } *)
    Definition bytes_addr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::HeapAddress"
            []
            []
            [
              M.cast
                (Ty.path "u16")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 16
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_bytes_addr :
      M.IsAssociatedFunction.C Self "bytes_addr" bytes_addr.
    Admitted.
    Global Typeclasses Opaque bytes_addr.
    
    (*     pub fn bytes_hdr_len(self) -> usize { (self.0 >> 8) as usize } *)
    Definition bytes_hdr_len (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.cast
            (Ty.path "usize")
            (M.call_closure (|
              Ty.path "u32",
              BinOp.Wrap.shr,
              [
                M.read (|
                  M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                |);
                Value.Integer IntegerKind.I32 8
              ]
            |))))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_bytes_hdr_len :
      M.IsAssociatedFunction.C Self "bytes_hdr_len" bytes_hdr_len.
    Admitted.
    Global Typeclasses Opaque bytes_hdr_len.
    
    (*
        pub fn int_value(self) -> i32 {
            (self.0 as i32) >> 8
        }
    *)
    Definition int_value (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "i32",
            BinOp.Wrap.shr,
            [
              M.cast
                (Ty.path "i32")
                (M.read (|
                  M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                |));
              Value.Integer IntegerKind.I32 8
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_int_value :
      M.IsAssociatedFunction.C Self "int_value" int_value.
    Admitted.
    Global Typeclasses Opaque int_value.
    
    (*     pub fn header_code_ptr(self) -> CodeAddress { CodeAddress((self.0 >> 16) as u16) } *)
    Definition header_code_ptr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::CodeAddress"
            []
            []
            [
              M.cast
                (Ty.path "u16")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 16
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_header_code_ptr :
      M.IsAssociatedFunction.C Self "header_code_ptr" header_code_ptr.
    Admitted.
    Global Typeclasses Opaque header_code_ptr.
    
    (*     pub fn header_env_len(self) -> u8 { (self.0 >> 8) as u8 } *)
    Definition header_env_len (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.cast
            (Ty.path "u8")
            (M.call_closure (|
              Ty.path "u32",
              BinOp.Wrap.shr,
              [
                M.read (|
                  M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                |);
                Value.Integer IntegerKind.I32 8
              ]
            |))))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_header_env_len :
      M.IsAssociatedFunction.C Self "header_env_len" header_env_len.
    Admitted.
    Global Typeclasses Opaque header_env_len.
    
    (*
        pub fn gc_header(size: u8) -> Self {
            debug_assert!(size < 128);
            Self(TYP_GC | (size as u32) << 8)
        }
    *)
    Definition gc_header (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ size ] =>
        ltac:(M.monadic
          (let size := M.alloc (| Ty.path "u8", size |) in
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.match_operator (|
                Ty.tuple [],
                M.alloc (| Ty.tuple [], Value.Tuple [] |),
                [
                  fun γ =>
                    ltac:(M.monadic
                      (let γ := M.use (M.alloc (| Ty.path "bool", Value.Bool true |)) in
                      let _ := is_constant_or_break_match (| M.read (| γ |), Value.Bool true |) in
                      M.read (|
                        let~ _ : Ty.tuple [] :=
                          M.match_operator (|
                            Ty.tuple [],
                            M.alloc (| Ty.tuple [], Value.Tuple [] |),
                            [
                              fun γ =>
                                ltac:(M.monadic
                                  (let γ :=
                                    M.use
                                      (M.alloc (|
                                        Ty.path "bool",
                                        M.call_closure (|
                                          Ty.path "bool",
                                          UnOp.not,
                                          [
                                            M.call_closure (|
                                              Ty.path "bool",
                                              BinOp.lt,
                                              [ M.read (| size |); Value.Integer IntegerKind.U8 128
                                              ]
                                            |)
                                          ]
                                        |)
                                      |)) in
                                  let _ :=
                                    is_constant_or_break_match (|
                                      M.read (| γ |),
                                      Value.Bool true
                                    |) in
                                  M.never_to_any (|
                                    M.call_closure (|
                                      Ty.path "never",
                                      M.get_function (| "core::panicking::panic", [], [] |),
                                      [ mk_str (| "assertion failed: size < 128" |) ]
                                    |)
                                  |)));
                              fun γ => ltac:(M.monadic (Value.Tuple []))
                            ]
                          |) in
                        M.alloc (| Ty.tuple [], Value.Tuple [] |)
                      |)));
                  fun γ => ltac:(M.monadic (Value.Tuple []))
                ]
              |) in
            M.alloc (|
              Ty.path "encore_vm::value::Value",
              Value.StructTuple
                "encore_vm::value::Value"
                []
                []
                [
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.bit_or,
                    [
                      M.read (| get_constant (| "encore_vm::value::TYP_GC", Ty.path "u32" |) |);
                      M.call_closure (|
                        Ty.path "u32",
                        BinOp.Wrap.shl,
                        [
                          M.cast (Ty.path "u32") (M.read (| size |));
                          Value.Integer IntegerKind.I32 8
                        ]
                      |)
                    ]
                  |)
                ]
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_gc_header :
      M.IsAssociatedFunction.C Self "gc_header" gc_header.
    Admitted.
    Global Typeclasses Opaque gc_header.
    
    (*     pub fn is_gc(self) -> bool { self.0 & 0xFF == TYP_GC } *)
    Definition is_gc (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.eq,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  Value.Integer IntegerKind.U32 255
                ]
              |);
              M.read (| get_constant (| "encore_vm::value::TYP_GC", Ty.path "u32" |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_gc : M.IsAssociatedFunction.C Self "is_gc" is_gc.
    Admitted.
    Global Typeclasses Opaque is_gc.
    
    (*     pub fn gc_size(self) -> u8 { ((self.0 >> 8) as u8) & 0x7F } *)
    Definition gc_size (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "u8",
            BinOp.Wrap.bit_and,
            [
              M.cast
                (Ty.path "u8")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 8
                  ]
                |));
              Value.Integer IntegerKind.U8 127
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_gc_size : M.IsAssociatedFunction.C Self "gc_size" gc_size.
    Admitted.
    Global Typeclasses Opaque gc_size.
    
    (*     pub fn gc_is_marked(self) -> bool { self.0 & GC_MARK_BIT != 0 } *)
    Definition gc_is_marked (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.call_closure (|
            Ty.path "bool",
            BinOp.ne,
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_and,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  M.read (| get_constant (| "encore_vm::value::GC_MARK_BIT", Ty.path "u32" |) |)
                ]
              |);
              Value.Integer IntegerKind.U32 0
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_gc_is_marked :
      M.IsAssociatedFunction.C Self "gc_is_marked" gc_is_marked.
    Admitted.
    Global Typeclasses Opaque gc_is_marked.
    
    (*     pub fn gc_set_mark(self) -> Self { Self(self.0 | GC_MARK_BIT) } *)
    Definition gc_set_mark (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.read (|
                    M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                  |);
                  M.read (| get_constant (| "encore_vm::value::GC_MARK_BIT", Ty.path "u32" |) |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_gc_set_mark :
      M.IsAssociatedFunction.C Self "gc_set_mark" gc_set_mark.
    Admitted.
    Global Typeclasses Opaque gc_set_mark.
    
    (*     pub fn gc_fwd(self) -> HeapAddress { HeapAddress((self.0 >> 16) as u16) } *)
    Definition gc_fwd (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::HeapAddress"
            []
            []
            [
              M.cast
                (Ty.path "u16")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 16
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_gc_fwd : M.IsAssociatedFunction.C Self "gc_fwd" gc_fwd.
    Admitted.
    Global Typeclasses Opaque gc_fwd.
    
    (*
        pub fn gc_set_fwd(self, addr: HeapAddress) -> Self {
            Self((self.0 & 0xFFFF) | (addr.raw() as u32) << 16)
        }
    *)
    Definition gc_set_fwd (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; addr ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          let addr := M.alloc (| Ty.path "encore_vm::value::HeapAddress", addr |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.bit_and,
                    [
                      M.read (|
                        M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                      |);
                      Value.Integer IntegerKind.U32 65535
                    ]
                  |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast
                        (Ty.path "u32")
                        (M.call_closure (|
                          Ty.path "u16",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::HeapAddress",
                            "raw",
                            [],
                            []
                          |),
                          [ M.read (| addr |) ]
                        |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_gc_set_fwd :
      M.IsAssociatedFunction.C Self "gc_set_fwd" gc_set_fwd.
    Admitted.
    Global Typeclasses Opaque gc_set_fwd.
    
    (*
        pub fn with_heap_addr(self, new: HeapAddress) -> Self {
            Self((self.0 & 0xFFFF) | (new.raw() as u32) << 16)
        }
    *)
    Definition with_heap_addr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; new ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          let new := M.alloc (| Ty.path "encore_vm::value::HeapAddress", new |) in
          Value.StructTuple
            "encore_vm::value::Value"
            []
            []
            [
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.bit_and,
                    [
                      M.read (|
                        M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                      |);
                      Value.Integer IntegerKind.U32 65535
                    ]
                  |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [
                      M.cast
                        (Ty.path "u32")
                        (M.call_closure (|
                          Ty.path "u16",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::HeapAddress",
                            "raw",
                            [],
                            []
                          |),
                          [ M.read (| new |) ]
                        |));
                      Value.Integer IntegerKind.I32 16
                    ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_with_heap_addr :
      M.IsAssociatedFunction.C Self "with_heap_addr" with_heap_addr.
    Admitted.
    Global Typeclasses Opaque with_heap_addr.
    
    (*
        pub fn has_heap_addr(self) -> bool {
            self.is_closure()
                || (self.is_ctor() && !self.heap_addr().is_null())
                || self.is_bytes()
        }
    *)
    Definition has_heap_addr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          LogicalOp.or (|
            LogicalOp.or (|
              M.call_closure (|
                Ty.path "bool",
                M.get_associated_function (|
                  Ty.path "encore_vm::value::Value",
                  "is_closure",
                  [],
                  []
                |),
                [ M.read (| self |) ]
              |),
              ltac:(M.monadic
                (LogicalOp.and (|
                  M.call_closure (|
                    Ty.path "bool",
                    M.get_associated_function (|
                      Ty.path "encore_vm::value::Value",
                      "is_ctor",
                      [],
                      []
                    |),
                    [ M.read (| self |) ]
                  |),
                  ltac:(M.monadic
                    (M.call_closure (|
                      Ty.path "bool",
                      UnOp.not,
                      [
                        M.call_closure (|
                          Ty.path "bool",
                          M.get_associated_function (|
                            Ty.path "encore_vm::value::HeapAddress",
                            "is_null",
                            [],
                            []
                          |),
                          [
                            M.call_closure (|
                              Ty.path "encore_vm::value::HeapAddress",
                              M.get_associated_function (|
                                Ty.path "encore_vm::value::Value",
                                "heap_addr",
                                [],
                                []
                              |),
                              [ M.read (| self |) ]
                            |)
                          ]
                        |)
                      ]
                    |)))
                |)))
            |),
            ltac:(M.monadic
              (M.call_closure (|
                Ty.path "bool",
                M.get_associated_function (|
                  Ty.path "encore_vm::value::Value",
                  "is_bytes",
                  [],
                  []
                |),
                [ M.read (| self |) ]
              |)))
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_has_heap_addr :
      M.IsAssociatedFunction.C Self "has_heap_addr" has_heap_addr.
    Admitted.
    Global Typeclasses Opaque has_heap_addr.
    
    (*     pub fn heap_addr(self) -> HeapAddress { HeapAddress((self.0 >> 16) as u16) } *)
    Definition heap_addr (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          Value.StructTuple
            "encore_vm::value::HeapAddress"
            []
            []
            [
              M.cast
                (Ty.path "u16")
                (M.call_closure (|
                  Ty.path "u32",
                  BinOp.Wrap.shr,
                  [
                    M.read (|
                      M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
                    |);
                    Value.Integer IntegerKind.I32 16
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_heap_addr :
      M.IsAssociatedFunction.C Self "heap_addr" heap_addr.
    Admitted.
    Global Typeclasses Opaque heap_addr.
    
    (*     pub fn to_u32(self) -> u32 { self.0 } *)
    Definition to_u32 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.path "encore_vm::value::Value", self |) in
          M.read (|
            M.SubPointer.get_struct_tuple_field (| self, "encore_vm::value::Value", 0 |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_to_u32 : M.IsAssociatedFunction.C Self "to_u32" to_u32.
    Admitted.
    Global Typeclasses Opaque to_u32.
    
    (*     pub fn from_u32(bits: u32) -> Self { Self(bits) } *)
    Definition from_u32 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ bits ] =>
        ltac:(M.monadic
          (let bits := M.alloc (| Ty.path "u32", bits |) in
          Value.StructTuple "encore_vm::value::Value" [] [] [ M.read (| bits |) ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_from_u32 : M.IsAssociatedFunction.C Self "from_u32" from_u32.
    Admitted.
    Global Typeclasses Opaque from_u32.
  End Impl_encore_vm_value_Value.
End value.
