(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module code.
  (* StructRecord
    {
      name := "Code";
      const_params := [];
      ty_params := [];
      fields :=
        [
          ("bytes", Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ] ]);
          ("pc", Ty.path "usize")
        ];
    } *)
  
  Module Impl_encore_vm_code_Code.
    Definition Self : Ty.t := Ty.path "encore_vm::code::Code".
    
    (*
        pub fn new(bytes: &'a [u8]) -> Self {
            Self { bytes, pc: 0 }
        }
    *)
    Definition new (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ bytes ] =>
        ltac:(M.monadic
          (let bytes :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ] ],
              bytes
            |) in
          Value.mkStructRecord
            "encore_vm::code::Code"
            []
            []
            [ ("bytes", M.read (| bytes |)); ("pc", Value.Integer IntegerKind.Usize 0) ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new : M.IsAssociatedFunction.C Self "new" new.
    Admitted.
    Global Typeclasses Opaque new.
    
    (*
        pub fn read_u8(&mut self) -> u8 {
            let b = unsafe { *self.bytes.get_unchecked(self.pc) };
            self.pc += 1;
            b
        }
    *)
    Definition read_u8 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          M.read (|
            let~ b : Ty.path "u8" :=
              M.read (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                    M.get_associated_function (|
                      Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                      "get_unchecked",
                      [],
                      [ Ty.path "usize" ]
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.deref (|
                          M.read (|
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| self |) |),
                              "encore_vm::code::Code",
                              "bytes"
                            |)
                          |)
                        |)
                      |);
                      M.read (|
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "encore_vm::code::Code",
                          "pc"
                        |)
                      |)
                    ]
                  |)
                |)
              |) in
            let~ _ : Ty.tuple [] :=
              let β :=
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "encore_vm::code::Code",
                  "pc"
                |) in
              M.write (|
                β,
                M.call_closure (|
                  Ty.path "usize",
                  BinOp.Wrap.add,
                  [ M.read (| β |); Value.Integer IntegerKind.Usize 1 ]
                |)
              |) in
            b
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_read_u8 : M.IsAssociatedFunction.C Self "read_u8" read_u8.
    Admitted.
    Global Typeclasses Opaque read_u8.
    
    (*
        pub fn read_u16(&mut self) -> u16 {
            let lo = unsafe { *self.bytes.get_unchecked(self.pc) } as u16;
            let hi = unsafe { *self.bytes.get_unchecked(self.pc + 1) } as u16;
            self.pc += 2;
            lo | (hi << 8)
        }
    *)
    Definition read_u16 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          M.read (|
            let~ lo : Ty.path "u16" :=
              M.cast
                (Ty.path "u16")
                (M.read (|
                  M.deref (|
                    M.call_closure (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                      M.get_associated_function (|
                        Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                        "get_unchecked",
                        [],
                        [ Ty.path "usize" ]
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "bytes"
                              |)
                            |)
                          |)
                        |);
                        M.read (|
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "encore_vm::code::Code",
                            "pc"
                          |)
                        |)
                      ]
                    |)
                  |)
                |)) in
            let~ hi : Ty.path "u16" :=
              M.cast
                (Ty.path "u16")
                (M.read (|
                  M.deref (|
                    M.call_closure (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                      M.get_associated_function (|
                        Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                        "get_unchecked",
                        [],
                        [ Ty.path "usize" ]
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "bytes"
                              |)
                            |)
                          |)
                        |);
                        M.call_closure (|
                          Ty.path "usize",
                          BinOp.Wrap.add,
                          [
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "pc"
                              |)
                            |);
                            Value.Integer IntegerKind.Usize 1
                          ]
                        |)
                      ]
                    |)
                  |)
                |)) in
            let~ _ : Ty.tuple [] :=
              let β :=
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "encore_vm::code::Code",
                  "pc"
                |) in
              M.write (|
                β,
                M.call_closure (|
                  Ty.path "usize",
                  BinOp.Wrap.add,
                  [ M.read (| β |); Value.Integer IntegerKind.Usize 2 ]
                |)
              |) in
            M.alloc (|
              Ty.path "u16",
              M.call_closure (|
                Ty.path "u16",
                BinOp.Wrap.bit_or,
                [
                  M.read (| lo |);
                  M.call_closure (|
                    Ty.path "u16",
                    BinOp.Wrap.shl,
                    [ M.read (| hi |); Value.Integer IntegerKind.I32 8 ]
                  |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_read_u16 : M.IsAssociatedFunction.C Self "read_u16" read_u16.
    Admitted.
    Global Typeclasses Opaque read_u16.
    
    (*
        pub fn read_u24(&mut self) -> u32 {
            let b0 = unsafe { *self.bytes.get_unchecked(self.pc) } as u32;
            let b1 = unsafe { *self.bytes.get_unchecked(self.pc + 1) } as u32;
            let b2 = unsafe { *self.bytes.get_unchecked(self.pc + 2) } as u32;
            self.pc += 3;
            b0 | (b1 << 8) | (b2 << 16)
        }
    *)
    Definition read_u24 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          M.read (|
            let~ b0 : Ty.path "u32" :=
              M.cast
                (Ty.path "u32")
                (M.read (|
                  M.deref (|
                    M.call_closure (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                      M.get_associated_function (|
                        Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                        "get_unchecked",
                        [],
                        [ Ty.path "usize" ]
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "bytes"
                              |)
                            |)
                          |)
                        |);
                        M.read (|
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "encore_vm::code::Code",
                            "pc"
                          |)
                        |)
                      ]
                    |)
                  |)
                |)) in
            let~ b1 : Ty.path "u32" :=
              M.cast
                (Ty.path "u32")
                (M.read (|
                  M.deref (|
                    M.call_closure (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                      M.get_associated_function (|
                        Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                        "get_unchecked",
                        [],
                        [ Ty.path "usize" ]
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "bytes"
                              |)
                            |)
                          |)
                        |);
                        M.call_closure (|
                          Ty.path "usize",
                          BinOp.Wrap.add,
                          [
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "pc"
                              |)
                            |);
                            Value.Integer IntegerKind.Usize 1
                          ]
                        |)
                      ]
                    |)
                  |)
                |)) in
            let~ b2 : Ty.path "u32" :=
              M.cast
                (Ty.path "u32")
                (M.read (|
                  M.deref (|
                    M.call_closure (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                      M.get_associated_function (|
                        Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                        "get_unchecked",
                        [],
                        [ Ty.path "usize" ]
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "bytes"
                              |)
                            |)
                          |)
                        |);
                        M.call_closure (|
                          Ty.path "usize",
                          BinOp.Wrap.add,
                          [
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "pc"
                              |)
                            |);
                            Value.Integer IntegerKind.Usize 2
                          ]
                        |)
                      ]
                    |)
                  |)
                |)) in
            let~ _ : Ty.tuple [] :=
              let β :=
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "encore_vm::code::Code",
                  "pc"
                |) in
              M.write (|
                β,
                M.call_closure (|
                  Ty.path "usize",
                  BinOp.Wrap.add,
                  [ M.read (| β |); Value.Integer IntegerKind.Usize 3 ]
                |)
              |) in
            M.alloc (|
              Ty.path "u32",
              M.call_closure (|
                Ty.path "u32",
                BinOp.Wrap.bit_or,
                [
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.bit_or,
                    [
                      M.read (| b0 |);
                      M.call_closure (|
                        Ty.path "u32",
                        BinOp.Wrap.shl,
                        [ M.read (| b1 |); Value.Integer IntegerKind.I32 8 ]
                      |)
                    ]
                  |);
                  M.call_closure (|
                    Ty.path "u32",
                    BinOp.Wrap.shl,
                    [ M.read (| b2 |); Value.Integer IntegerKind.I32 16 ]
                  |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_read_u24 : M.IsAssociatedFunction.C Self "read_u24" read_u24.
    Admitted.
    Global Typeclasses Opaque read_u24.
    
    (*
        pub fn read_reg(&mut self) -> Reg {
            Reg::new(self.read_u8())
        }
    *)
    Definition read_reg (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          M.call_closure (|
            Ty.path "encore_vm::value::Reg",
            M.get_associated_function (| Ty.path "encore_vm::value::Reg", "new", [], [] |),
            [
              M.call_closure (|
                Ty.path "u8",
                M.get_associated_function (| Ty.path "encore_vm::code::Code", "read_u8", [], [] |),
                [ M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |) ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_read_reg : M.IsAssociatedFunction.C Self "read_reg" read_reg.
    Admitted.
    Global Typeclasses Opaque read_reg.
    
    (*
        pub fn read_address(&mut self) -> CodeAddress {
            CodeAddress::new(self.read_u16())
        }
    *)
    Definition read_address (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          M.call_closure (|
            Ty.path "encore_vm::value::CodeAddress",
            M.get_associated_function (| Ty.path "encore_vm::value::CodeAddress", "new", [], [] |),
            [
              M.call_closure (|
                Ty.path "u16",
                M.get_associated_function (| Ty.path "encore_vm::code::Code", "read_u16", [], [] |),
                [ M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |) ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_read_address :
      M.IsAssociatedFunction.C Self "read_address" read_address.
    Admitted.
    Global Typeclasses Opaque read_address.
    
    (*
        pub fn read_address_at(&self, pos: usize) -> CodeAddress {
            let lo = unsafe { *self.bytes.get_unchecked(pos) } as u16;
            let hi = unsafe { *self.bytes.get_unchecked(pos + 1) } as u16;
            CodeAddress::new(lo | (hi << 8))
        }
    *)
    Definition read_address_at (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; pos ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          let pos := M.alloc (| Ty.path "usize", pos |) in
          M.read (|
            let~ lo : Ty.path "u16" :=
              M.cast
                (Ty.path "u16")
                (M.read (|
                  M.deref (|
                    M.call_closure (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                      M.get_associated_function (|
                        Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                        "get_unchecked",
                        [],
                        [ Ty.path "usize" ]
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "bytes"
                              |)
                            |)
                          |)
                        |);
                        M.read (| pos |)
                      ]
                    |)
                  |)
                |)) in
            let~ hi : Ty.path "u16" :=
              M.cast
                (Ty.path "u16")
                (M.read (|
                  M.deref (|
                    M.call_closure (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                      M.get_associated_function (|
                        Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ],
                        "get_unchecked",
                        [],
                        [ Ty.path "usize" ]
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.read (|
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "encore_vm::code::Code",
                                "bytes"
                              |)
                            |)
                          |)
                        |);
                        M.call_closure (|
                          Ty.path "usize",
                          BinOp.Wrap.add,
                          [ M.read (| pos |); Value.Integer IntegerKind.Usize 1 ]
                        |)
                      ]
                    |)
                  |)
                |)) in
            M.alloc (|
              Ty.path "encore_vm::value::CodeAddress",
              M.call_closure (|
                Ty.path "encore_vm::value::CodeAddress",
                M.get_associated_function (|
                  Ty.path "encore_vm::value::CodeAddress",
                  "new",
                  [],
                  []
                |),
                [
                  M.call_closure (|
                    Ty.path "u16",
                    BinOp.Wrap.bit_or,
                    [
                      M.read (| lo |);
                      M.call_closure (|
                        Ty.path "u16",
                        BinOp.Wrap.shl,
                        [ M.read (| hi |); Value.Integer IntegerKind.I32 8 ]
                      |)
                    ]
                  |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_read_address_at :
      M.IsAssociatedFunction.C Self "read_address_at" read_address_at.
    Admitted.
    Global Typeclasses Opaque read_address_at.
    
    (*
        pub fn jump(&mut self, target: CodeAddress) {
            self.pc = target.raw() as usize;
        }
    *)
    Definition jump (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; target ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          let target := M.alloc (| Ty.path "encore_vm::value::CodeAddress", target |) in
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.write (|
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "encore_vm::code::Code",
                  "pc"
                |),
                M.cast
                  (Ty.path "usize")
                  (M.call_closure (|
                    Ty.path "u16",
                    M.get_associated_function (|
                      Ty.path "encore_vm::value::CodeAddress",
                      "raw",
                      [],
                      []
                    |),
                    [ M.read (| target |) ]
                  |))
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_jump : M.IsAssociatedFunction.C Self "jump" jump.
    Admitted.
    Global Typeclasses Opaque jump.
    
    (*
        pub fn skip(&mut self, n: usize) {
            self.pc += n;
        }
    *)
    Definition skip (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; n ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          let n := M.alloc (| Ty.path "usize", n |) in
          M.read (|
            let~ _ : Ty.tuple [] :=
              let β :=
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "encore_vm::code::Code",
                  "pc"
                |) in
              M.write (|
                β,
                M.call_closure (|
                  Ty.path "usize",
                  BinOp.Wrap.add,
                  [ M.read (| β |); M.read (| n |) ]
                |)
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_skip : M.IsAssociatedFunction.C Self "skip" skip.
    Admitted.
    Global Typeclasses Opaque skip.
    
    (*
        pub fn pc(&self) -> usize {
            self.pc
        }
    *)
    Definition pc (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::code::Code" ], self |) in
          M.read (|
            M.SubPointer.get_struct_record_field (|
              M.deref (| M.read (| self |) |),
              "encore_vm::code::Code",
              "pc"
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_pc : M.IsAssociatedFunction.C Self "pc" pc.
    Admitted.
    Global Typeclasses Opaque pc.
  End Impl_encore_vm_code_Code.
End code.
