(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module error.
  (*
  Enum VmError
  {
    const_params := [];
    ty_params := [];
    variants :=
      [
        {
          name := "HeapOverflow";
          item := StructTuple [];
        };
        {
          name := "InvalidOpcode";
          item := StructTuple [ Ty.path "u8" ];
        };
        {
          name := "NotRegistered";
          item := StructTuple [ Ty.path "u16" ];
        };
        {
          name := "MatchFail";
          item := StructTuple [];
        };
        {
          name := "ByteRange";
          item := StructTuple [ Ty.path "i32" ];
        };
        {
          name := "BadMagic";
          item := StructTuple [];
        };
        {
          name := "Truncated";
          item := StructTuple [];
        }
      ];
  }
  *)
  
  Axiom IsDiscriminant_VmError_HeapOverflow :
    M.IsDiscriminant "encore_vm::error::VmError::HeapOverflow" 0.
  Axiom IsDiscriminant_VmError_InvalidOpcode :
    M.IsDiscriminant "encore_vm::error::VmError::InvalidOpcode" 1.
  Axiom IsDiscriminant_VmError_NotRegistered :
    M.IsDiscriminant "encore_vm::error::VmError::NotRegistered" 2.
  Axiom IsDiscriminant_VmError_MatchFail :
    M.IsDiscriminant "encore_vm::error::VmError::MatchFail" 3.
  Axiom IsDiscriminant_VmError_ByteRange :
    M.IsDiscriminant "encore_vm::error::VmError::ByteRange" 4.
  Axiom IsDiscriminant_VmError_BadMagic : M.IsDiscriminant "encore_vm::error::VmError::BadMagic" 5.
  Axiom IsDiscriminant_VmError_Truncated :
    M.IsDiscriminant "encore_vm::error::VmError::Truncated" 6.
  
  Module Impl_core_fmt_Debug_for_encore_vm_error_VmError.
    Definition Self : Ty.t := Ty.path "encore_vm::error::VmError".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::error::VmError" ], self |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let _ := M.is_struct_tuple (| γ, "encore_vm::error::VmError::HeapOverflow" |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "write_str",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "HeapOverflow" |) |) |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "encore_vm::error::VmError::InvalidOpcode",
                      0
                    |) in
                  let __self_0 := M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "u8" ], γ1_0 |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "InvalidOpcode" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "&") [] [ Ty.path "u8" ] ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "encore_vm::error::VmError::NotRegistered",
                      0
                    |) in
                  let __self_0 := M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "u16" ], γ1_0 |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "NotRegistered" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.apply (Ty.path "&") [] [ Ty.path "u16" ] ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let _ := M.is_struct_tuple (| γ, "encore_vm::error::VmError::MatchFail" |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "write_str",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "MatchFail" |) |) |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "encore_vm::error::VmError::ByteRange",
                      0
                    |) in
                  let __self_0 := M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "i32" ], γ1_0 |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "ByteRange" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.apply (Ty.path "&") [] [ Ty.path "i32" ] ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let _ := M.is_struct_tuple (| γ, "encore_vm::error::VmError::BadMagic" |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "write_str",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "BadMagic" |) |) |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let _ := M.is_struct_tuple (| γ, "encore_vm::error::VmError::Truncated" |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "write_str",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Truncated" |) |) |)
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_encore_vm_error_VmError.
  
  Module Impl_core_clone_Clone_for_encore_vm_error_VmError.
    Definition Self : Ty.t := Ty.path "encore_vm::error::VmError".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::error::VmError" ], self |) in
          M.match_operator (|
            Ty.path "encore_vm::error::VmError",
            Value.DeclaredButUndefined,
            [
              fun γ =>
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.path "encore_vm::error::VmError",
                    Value.DeclaredButUndefined,
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (M.match_operator (|
                            Ty.path "encore_vm::error::VmError",
                            Value.DeclaredButUndefined,
                            [
                              fun γ =>
                                ltac:(M.monadic (M.read (| M.deref (| M.read (| self |) |) |)))
                            ]
                          |)))
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_encore_vm_error_VmError.
  
  Module Impl_core_marker_Copy_for_encore_vm_error_VmError.
    Definition Self : Ty.t := Ty.path "encore_vm::error::VmError".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::Copy"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_Copy_for_encore_vm_error_VmError.
  
  Module Impl_core_marker_StructuralPartialEq_for_encore_vm_error_VmError.
    Definition Self : Ty.t := Ty.path "encore_vm::error::VmError".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::StructuralPartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_StructuralPartialEq_for_encore_vm_error_VmError.
  
  Module Impl_core_cmp_PartialEq_encore_vm_error_VmError_for_encore_vm_error_VmError.
    Definition Self : Ty.t := Ty.path "encore_vm::error::VmError".
    
    (* PartialEq *)
    Definition eq (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; other ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::error::VmError" ], self |) in
          let other :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::error::VmError" ],
              other
            |) in
          M.read (|
            let~ __self_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "encore_vm::error::VmError" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
              |) in
            let~ __arg1_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "encore_vm::error::VmError" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| other |) |) |) ]
              |) in
            M.alloc (|
              Ty.path "bool",
              LogicalOp.and (|
                M.call_closure (|
                  Ty.path "bool",
                  BinOp.eq,
                  [ M.read (| __self_discr |); M.read (| __arg1_discr |) ]
                |),
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.path "bool",
                    M.alloc (|
                      Ty.tuple
                        [
                          Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::error::VmError" ];
                          Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::error::VmError" ]
                        ],
                      Value.Tuple [ M.read (| self |); M.read (| other |) ]
                    |),
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                          let γ0_0 := M.deref (| M.read (| γ0_0 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_0,
                              "encore_vm::error::VmError::InvalidOpcode",
                              0
                            |) in
                          let __self_0 :=
                            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "u8" ], γ2_0 |) in
                          let γ0_1 := M.deref (| M.read (| γ0_1 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_1,
                              "encore_vm::error::VmError::InvalidOpcode",
                              0
                            |) in
                          let __arg1_0 :=
                            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "u8" ], γ2_0 |) in
                          M.call_closure (|
                            Ty.path "bool",
                            M.get_trait_method (|
                              "core::cmp::PartialEq",
                              Ty.apply (Ty.path "&") [] [ Ty.path "u8" ],
                              [],
                              [ Ty.apply (Ty.path "&") [] [ Ty.path "u8" ] ],
                              "eq",
                              [],
                              []
                            |),
                            [
                              M.borrow (| Pointer.Kind.Ref, __self_0 |);
                              M.borrow (| Pointer.Kind.Ref, __arg1_0 |)
                            ]
                          |)));
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                          let γ0_0 := M.deref (| M.read (| γ0_0 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_0,
                              "encore_vm::error::VmError::NotRegistered",
                              0
                            |) in
                          let __self_0 :=
                            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "u16" ], γ2_0 |) in
                          let γ0_1 := M.deref (| M.read (| γ0_1 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_1,
                              "encore_vm::error::VmError::NotRegistered",
                              0
                            |) in
                          let __arg1_0 :=
                            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "u16" ], γ2_0 |) in
                          M.call_closure (|
                            Ty.path "bool",
                            M.get_trait_method (|
                              "core::cmp::PartialEq",
                              Ty.apply (Ty.path "&") [] [ Ty.path "u16" ],
                              [],
                              [ Ty.apply (Ty.path "&") [] [ Ty.path "u16" ] ],
                              "eq",
                              [],
                              []
                            |),
                            [
                              M.borrow (| Pointer.Kind.Ref, __self_0 |);
                              M.borrow (| Pointer.Kind.Ref, __arg1_0 |)
                            ]
                          |)));
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                          let γ0_0 := M.deref (| M.read (| γ0_0 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_0,
                              "encore_vm::error::VmError::ByteRange",
                              0
                            |) in
                          let __self_0 :=
                            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "i32" ], γ2_0 |) in
                          let γ0_1 := M.deref (| M.read (| γ0_1 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_1,
                              "encore_vm::error::VmError::ByteRange",
                              0
                            |) in
                          let __arg1_0 :=
                            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "i32" ], γ2_0 |) in
                          M.call_closure (|
                            Ty.path "bool",
                            M.get_trait_method (|
                              "core::cmp::PartialEq",
                              Ty.apply (Ty.path "&") [] [ Ty.path "i32" ],
                              [],
                              [ Ty.apply (Ty.path "&") [] [ Ty.path "i32" ] ],
                              "eq",
                              [],
                              []
                            |),
                            [
                              M.borrow (| Pointer.Kind.Ref, __self_0 |);
                              M.borrow (| Pointer.Kind.Ref, __arg1_0 |)
                            ]
                          |)));
                      fun γ => ltac:(M.monadic (Value.Bool true))
                    ]
                  |)))
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::PartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) [ Ty.path "encore_vm::error::VmError" ]
        Self
        (* Instance *) [ ("eq", InstanceField.Method eq) ].
  End Impl_core_cmp_PartialEq_encore_vm_error_VmError_for_encore_vm_error_VmError.
  
  Module Impl_core_cmp_Eq_for_encore_vm_error_VmError.
    Definition Self : Ty.t := Ty.path "encore_vm::error::VmError".
    
    (* Eq *)
    Definition assert_receiver_is_total_eq
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "encore_vm::error::VmError" ], self |) in
          M.match_operator (|
            Ty.tuple [],
            Value.DeclaredButUndefined,
            [
              fun γ =>
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.tuple [],
                    Value.DeclaredButUndefined,
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (M.match_operator (|
                            Ty.tuple [],
                            Value.DeclaredButUndefined,
                            [ fun γ => ltac:(M.monadic (Value.Tuple [])) ]
                          |)))
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::Eq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *)
        [ ("assert_receiver_is_total_eq", InstanceField.Method assert_receiver_is_total_eq) ].
  End Impl_core_cmp_Eq_for_encore_vm_error_VmError.
End error.
