(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module opcode.
  Definition value_FIN (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 0 |))).
  
  Global Instance Instance_IsConstant_value_FIN : M.IsFunction.C "encore_vm::opcode::FIN" value_FIN.
  Admitted.
  Global Typeclasses Opaque value_FIN.
  
  Definition value_MOV (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 1 |))).
  
  Global Instance Instance_IsConstant_value_MOV : M.IsFunction.C "encore_vm::opcode::MOV" value_MOV.
  Admitted.
  Global Typeclasses Opaque value_MOV.
  
  Definition value_CAPTURE (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 2 |))).
  
  Global Instance Instance_IsConstant_value_CAPTURE :
    M.IsFunction.C "encore_vm::opcode::CAPTURE" value_CAPTURE.
  Admitted.
  Global Typeclasses Opaque value_CAPTURE.
  
  Definition value_GLOBAL (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 3 |))).
  
  Global Instance Instance_IsConstant_value_GLOBAL :
    M.IsFunction.C "encore_vm::opcode::GLOBAL" value_GLOBAL.
  Admitted.
  Global Typeclasses Opaque value_GLOBAL.
  
  Definition value_CLOSURE (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 6 |))).
  
  Global Instance Instance_IsConstant_value_CLOSURE :
    M.IsFunction.C "encore_vm::opcode::CLOSURE" value_CLOSURE.
  Admitted.
  Global Typeclasses Opaque value_CLOSURE.
  
  Definition value_PACK (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 7 |))).
  
  Global Instance Instance_IsConstant_value_PACK :
    M.IsFunction.C "encore_vm::opcode::PACK" value_PACK.
  Admitted.
  Global Typeclasses Opaque value_PACK.
  
  Definition value_FIELD (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 8 |))).
  
  Global Instance Instance_IsConstant_value_FIELD :
    M.IsFunction.C "encore_vm::opcode::FIELD" value_FIELD.
  Admitted.
  Global Typeclasses Opaque value_FIELD.
  
  Definition value_MATCH (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 9 |))).
  
  Global Instance Instance_IsConstant_value_MATCH :
    M.IsFunction.C "encore_vm::opcode::MATCH" value_MATCH.
  Admitted.
  Global Typeclasses Opaque value_MATCH.
  
  Definition value_ENCORE (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 10 |))).
  
  Global Instance Instance_IsConstant_value_ENCORE :
    M.IsFunction.C "encore_vm::opcode::ENCORE" value_ENCORE.
  Admitted.
  Global Typeclasses Opaque value_ENCORE.
  
  Definition value_FUNCTION (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 13 |))).
  
  Global Instance Instance_IsConstant_value_FUNCTION :
    M.IsFunction.C "encore_vm::opcode::FUNCTION" value_FUNCTION.
  Admitted.
  Global Typeclasses Opaque value_FUNCTION.
  
  Definition value_UNPACK (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 14 |))).
  
  Global Instance Instance_IsConstant_value_UNPACK :
    M.IsFunction.C "encore_vm::opcode::UNPACK" value_UNPACK.
  Admitted.
  Global Typeclasses Opaque value_UNPACK.
  
  Definition value_INT (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 16 |))).
  
  Global Instance Instance_IsConstant_value_INT : M.IsFunction.C "encore_vm::opcode::INT" value_INT.
  Admitted.
  Global Typeclasses Opaque value_INT.
  
  Definition value_INT_ADD (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 17 |))).
  
  Global Instance Instance_IsConstant_value_INT_ADD :
    M.IsFunction.C "encore_vm::opcode::INT_ADD" value_INT_ADD.
  Admitted.
  Global Typeclasses Opaque value_INT_ADD.
  
  Definition value_INT_SUB (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 18 |))).
  
  Global Instance Instance_IsConstant_value_INT_SUB :
    M.IsFunction.C "encore_vm::opcode::INT_SUB" value_INT_SUB.
  Admitted.
  Global Typeclasses Opaque value_INT_SUB.
  
  Definition value_INT_MUL (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 19 |))).
  
  Global Instance Instance_IsConstant_value_INT_MUL :
    M.IsFunction.C "encore_vm::opcode::INT_MUL" value_INT_MUL.
  Admitted.
  Global Typeclasses Opaque value_INT_MUL.
  
  Definition value_INT_EQ (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 20 |))).
  
  Global Instance Instance_IsConstant_value_INT_EQ :
    M.IsFunction.C "encore_vm::opcode::INT_EQ" value_INT_EQ.
  Admitted.
  Global Typeclasses Opaque value_INT_EQ.
  
  Definition value_INT_LT (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 21 |))).
  
  Global Instance Instance_IsConstant_value_INT_LT :
    M.IsFunction.C "encore_vm::opcode::INT_LT" value_INT_LT.
  Admitted.
  Global Typeclasses Opaque value_INT_LT.
  
  Definition value_INT_BYTE (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 22 |))).
  
  Global Instance Instance_IsConstant_value_INT_BYTE :
    M.IsFunction.C "encore_vm::opcode::INT_BYTE" value_INT_BYTE.
  Admitted.
  Global Typeclasses Opaque value_INT_BYTE.
  
  Definition value_INT_0 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 24 |))).
  
  Global Instance Instance_IsConstant_value_INT_0 :
    M.IsFunction.C "encore_vm::opcode::INT_0" value_INT_0.
  Admitted.
  Global Typeclasses Opaque value_INT_0.
  
  Definition value_INT_1 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 25 |))).
  
  Global Instance Instance_IsConstant_value_INT_1 :
    M.IsFunction.C "encore_vm::opcode::INT_1" value_INT_1.
  Admitted.
  Global Typeclasses Opaque value_INT_1.
  
  Definition value_INT_2 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 26 |))).
  
  Global Instance Instance_IsConstant_value_INT_2 :
    M.IsFunction.C "encore_vm::opcode::INT_2" value_INT_2.
  Admitted.
  Global Typeclasses Opaque value_INT_2.
  
  Definition value_EXTERN (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 32 |))).
  
  Global Instance Instance_IsConstant_value_EXTERN :
    M.IsFunction.C "encore_vm::opcode::EXTERN" value_EXTERN.
  Admitted.
  Global Typeclasses Opaque value_EXTERN.
  
  Definition value_BYTES (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 48 |))).
  
  Global Instance Instance_IsConstant_value_BYTES :
    M.IsFunction.C "encore_vm::opcode::BYTES" value_BYTES.
  Admitted.
  Global Typeclasses Opaque value_BYTES.
  
  Definition value_BYTES_LEN (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 49 |))).
  
  Global Instance Instance_IsConstant_value_BYTES_LEN :
    M.IsFunction.C "encore_vm::opcode::BYTES_LEN" value_BYTES_LEN.
  Admitted.
  Global Typeclasses Opaque value_BYTES_LEN.
  
  Definition value_BYTES_GET (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 50 |))).
  
  Global Instance Instance_IsConstant_value_BYTES_GET :
    M.IsFunction.C "encore_vm::opcode::BYTES_GET" value_BYTES_GET.
  Admitted.
  Global Typeclasses Opaque value_BYTES_GET.
  
  Definition value_BYTES_CONCAT (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 51 |))).
  
  Global Instance Instance_IsConstant_value_BYTES_CONCAT :
    M.IsFunction.C "encore_vm::opcode::BYTES_CONCAT" value_BYTES_CONCAT.
  Admitted.
  Global Typeclasses Opaque value_BYTES_CONCAT.
  
  Definition value_BYTES_SLICE (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 52 |))).
  
  Global Instance Instance_IsConstant_value_BYTES_SLICE :
    M.IsFunction.C "encore_vm::opcode::BYTES_SLICE" value_BYTES_SLICE.
  Admitted.
  Global Typeclasses Opaque value_BYTES_SLICE.
  
  Definition value_BYTES_EQ (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 53 |))).
  
  Global Instance Instance_IsConstant_value_BYTES_EQ :
    M.IsFunction.C "encore_vm::opcode::BYTES_EQ" value_BYTES_EQ.
  Admitted.
  Global Typeclasses Opaque value_BYTES_EQ.
  
  Definition value_NULL (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u8", Value.Integer IntegerKind.U8 255 |))).
  
  Global Instance Instance_IsConstant_value_NULL :
    M.IsFunction.C "encore_vm::opcode::NULL" value_NULL.
  Admitted.
  Global Typeclasses Opaque value_NULL.
End opcode.
