;; This extracted scheme code relies on some additional macros
;; available at http://www.pps.univ-paris-diderot.fr/~letouzey/scheme
(load "macros_extr.scm")


(define add (lambda (a) (lambda (b) (+ a b))))
  
(define sub (lambda (a) (lambda (b) (int-sub-sat a b))))
  
(define leb (lambda (a) (lambda (b) (<= a b))))
  
(define ltb (lambda (a) (lambda (b) (< a b))))

(define divmod (lambdas (x y q u)
  ((lambdas (fO fS n) (if (= n 0) (fO 0) (fS (- n 1))))
     (lambda (_) `(Pair ,q ,u))
     (lambda (x~)
     ((lambdas (fO fS n) (if (= n 0) (fO 0) (fS (- n 1))))
        (lambda (_) (@ divmod x~ y `((lambda (x) (+ x 1)) ,q) y))
        (lambda (u~) (@ divmod x~ y q u~))
        u))
     x)))
  
(define div (lambda (a) (lambda (b) (int-div a b))))

(define modulo (lambda (a) (lambda (b) (int-mod a b))))

(define fold_left (lambdas (f l a0)
  (match l
     ((Nil) a0)
     ((Cons b l0) (@ fold_left f l0 (@ f a0 b))))))
  
(define bytes_of_string (lambda (s) s))

(define bytes_len (lambda (b) (bytes-len b)))

(define bytes_concat (lambda (a) (lambda (b) (bytes-concat a b))))

(define bytes_eqb (lambda (a) (lambda (b) (bytes-eq a b))))

(define byte_of_nat (lambda (n) (int->byte n)))

(define digits_aux (lambdas (fuel n acc)
  ((lambdas (fO fS n) (if (= n 0) (fO 0) (fS (- n 1))))
     (lambda (_) acc)
     (lambda (fuel~)
     (match (@ ltb n `((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`(0))))))))))))
        ((True) `(Cons ,n ,acc))
        ((False)
          (@ digits_aux fuel~
            (@ div n `((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
              ,`(0))))))))))))
            `(Cons
            ,(@ modulo n `((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
               ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
               ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
               ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
               ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
               ,`(0))))))))))))
            ,acc)))))
     fuel)))
  
(define digits (lambda (n) (@ digits_aux n n `(Nil))))

(define render (lambda (n)
  (@ fold_left (lambdas (acc d)
    (@ bytes_concat acc
      (byte_of_nat
        (@ add `((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
          ,`(0))))))))))))))))))))))))))))))))))))))))))))))))) d))))
    (digits n)
    (bytes_of_string `(String ,`(Ascii ,`(False) ,`(True) ,`(True) ,`(True)
      ,`(False) ,`(True) ,`(True) ,`(False)) ,`(String ,`(Ascii ,`(True)
      ,`(False) ,`(True) ,`(True) ,`(True) ,`(True) ,`(False) ,`(False))
      ,`(EmptyString)))))))

(define main render)

(define check
  (let ((r
    (render `((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`((lambda (x) (+ x 1)) ,`((lambda (x) (+ x 1))
      ,`(0)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
    (match (@ bytes_eqb r
             (bytes_of_string `(String ,`(Ascii ,`(False) ,`(True) ,`(True)
               ,`(True) ,`(False) ,`(True) ,`(True) ,`(False)) ,`(String
               ,`(Ascii ,`(True) ,`(False) ,`(True) ,`(True) ,`(True)
               ,`(True) ,`(False) ,`(False)) ,`(String ,`(Ascii ,`(True)
               ,`(False) ,`(False) ,`(True) ,`(True) ,`(True) ,`(False)
               ,`(False)) ,`(String ,`(Ascii ,`(False) ,`(False) ,`(False)
               ,`(False) ,`(True) ,`(True) ,`(False) ,`(False)) ,`(String
               ,`(Ascii ,`(True) ,`(True) ,`(True) ,`(False) ,`(True)
               ,`(True) ,`(False) ,`(False)) ,`(EmptyString))))))))
       ((True) (bytes_len r))
       ((False) `(0)))))

